"""
Chat service - project brief section 11 (AI Chat Interface persistence).

Wraps rag_service.answer_question (Phase 6, unchanged and still purely
stateless/testable on its own) with conversation and message persistence:
one call here is "ask a question in a conversation," which means creating
or continuing a Conversation, recording the user's Message, running RAG,
recording the assistant's Message and its MessageSource citations, and
updating the conversation's title/updated_at.

Design decisions:
- Conversations are private to the user who had them - there's no
  admin-visibility exception, unlike documents. A conversation reflects a
  person's own Q&A session, not organizational knowledge; get_for_user
  filters by user_id for every role, including ADMIN.
- No separate "create conversation" endpoint - a conversation only becomes
  meaningful once it has a first question, so POST /api/chat without a
  conversation_id both creates the conversation and asks the first question
  in one call, returning the new conversation_id.
- The conversation's title is derived from the first question (truncated),
  not generated by a second LLM call - keeps this from spending an extra
  API call purely on cosmetics. A nicer LLM-generated title is a reasonable
  future improvement.
- Historical citations are never re-checked against live document RBAC:
  once you asked a question and got an answer, that answer (and its
  citations) is your own conversation history, not a live view onto
  documents. If the underlying document/chunk is later deleted, the FK's
  ON DELETE SET NULL (see MessageSource) means the citation degrades
  gracefully (relevance_score is kept, document/chunk details become null)
  rather than the message disappearing.
"""
import uuid
from dataclasses import dataclass
from typing import List, Optional

from sqlalchemy.ext.asyncio import AsyncSession

from app.ai.embedding_provider import EmbeddingProvider
from app.ai.llm_provider import LLMProvider
from app.models.conversation import Conversation
from app.models.enums import MessageRole
from app.models.message import Message
from app.models.user import User
from app.repositories import conversation_repository, message_repository
from app.schemas.search import SearchResultItem
from app.services import rag_service
from app.utils.errors import ConversationNotFoundError

_TITLE_MAX_LENGTH = 60


def _derive_title(question: str) -> str:
    question = question.strip()
    if len(question) <= _TITLE_MAX_LENGTH:
        return question
    return question[: _TITLE_MAX_LENGTH - 1].rstrip() + "\u2026"


@dataclass
class ChatTurnResult:
    conversation: Conversation
    user_message: Message
    assistant_message: Message
    answer: str
    sources: List[SearchResultItem]


async def send_message(
    session: AsyncSession,
    user: User,
    question: str,
    *,
    conversation_id: Optional[uuid.UUID] = None,
    top_k: Optional[int] = None,
    similarity_threshold: Optional[float] = None,
    embedding_provider: Optional[EmbeddingProvider] = None,
    llm_provider: Optional[LLMProvider] = None,
) -> ChatTurnResult:
    if conversation_id is not None:
        conversation = await conversation_repository.get_for_user(session, user.id, conversation_id)
        if conversation is None:
            raise ConversationNotFoundError(f"Conversation '{conversation_id}' does not exist.")
    else:
        conversation = await conversation_repository.create(session, user.id)

    user_message = await message_repository.create_message(
        session, conversation_id=conversation.id, role=MessageRole.USER, content=question
    )

    result = await rag_service.answer_question(
        session,
        user,
        question,
        top_k=top_k,
        similarity_threshold=similarity_threshold,
        embedding_provider=embedding_provider,
        llm_provider=llm_provider,
    )

    assistant_message = await message_repository.create_message(
        session, conversation_id=conversation.id, role=MessageRole.ASSISTANT, content=result.answer
    )
    if result.sources:
        await message_repository.create_sources(session, assistant_message.id, result.sources)

    if conversation.title is None:
        conversation.title = _derive_title(question)
    await conversation_repository.touch(session, conversation)

    return ChatTurnResult(
        conversation=conversation,
        user_message=user_message,
        assistant_message=assistant_message,
        answer=result.answer,
        sources=result.sources,
    )


async def list_conversations(session: AsyncSession, user: User, *, skip: int = 0, limit: int = 50):
    return await conversation_repository.list_for_user(session, user.id, skip=skip, limit=limit)


async def get_conversation_with_messages(session: AsyncSession, user: User, conversation_id: uuid.UUID):
    conversation = await conversation_repository.get_for_user(session, user.id, conversation_id)
    if conversation is None:
        raise ConversationNotFoundError(f"Conversation '{conversation_id}' does not exist.")
    messages = await message_repository.list_with_sources_for_conversation(session, conversation.id)
    return conversation, messages


async def delete_conversation(session: AsyncSession, user: User, conversation_id: uuid.UUID) -> None:
    conversation = await conversation_repository.get_for_user(session, user.id, conversation_id)
    if conversation is None:
        raise ConversationNotFoundError(f"Conversation '{conversation_id}' does not exist.")
    await conversation_repository.delete(session, conversation)
